name: Deploy LostNFoundAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current directory
      run: pwd

    - name: List files
      run: ls -al

    - name: Install dependencies and build
      run: |
        npm install

    - name: Deploy to primary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_PRIMARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/reclaim4242/api/LostNFoundAPI
          git pull origin main
          npm install
          pm2 restart all
          sudo systemctl restart nginx

    - name: Deploy to secondary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_SECONDARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/reclaim4242/api/LostNFoundAPI
          git pull origin main
          npm install
          pm2 restart all
          sudo systemctl restart nginx
