name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
      working-directory: ./api/LostNFoundAPI

    - name: Deploy to primary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_PRIMARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 stop all
          cd /home/${{ secrets.SERVER_USER }}/api/LostNFoundAPI
          git pull origin main
          npm install
          pm2 start all
          sudo systemctl restart nginx

    - name: Deploy to secondary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_SECONDARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 stop all
          cd /home/${{ secrets.SERVER_USER }}/api/LostNFoundAPI
          git pull origin main
          npm install
          pm2 start all
          sudo systemctl restart nginx
